//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeendokListaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ertekezlet
    {
        public int id { get; set; }
        public string nev { get; set; }
        public System.DateTime kezdet_datum { get; set; }
        public Nullable<System.DateTime> veg_datum { get; set; }
        public string leiras { get; set; }
        public Nullable<int> letszam { get; set; }
        public bool online { get; set; }
    }
}
