//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeendokListaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feladat
    {
        public int id { get; set; }
        public string cim { get; set; }
        public string szoveg { get; set; }
        public System.DateTime letrehozas_datum { get; set; }
        public bool teljesitve { get; set; }
        public int felhasznalo_id { get; set; }
    
        public virtual felhasznalo felhasznalo { get; set; }
    }
}
